function RequisitionFormController($scope) {

  $scope.requisitionColumns =
    [
      {"id":1, "name":"productCode", "position":1, "source":{"description":"Reference Data", "name":"REFERENCE", "code":"R"}, "sourceConfigurable":null, "label":"Product Code", "formula":"", "indicator":"O", "used":true, "visible":true, "mandatory":true, "description":"Unique identifier for each commodity", "formulaValidationRequired":true},
      {"id":2, "name":"product", "position":2, "source":{"description":"Reference Data", "name":"REFERENCE", "code":"R"}, "sourceConfigurable":null, "label":"Product", "formula":"", "indicator":"R", "used":true, "visible":true, "mandatory":true, "description":"Primary name of the product", "formulaValidationRequired":true},
      {"id":3, "name":"dispensingUnit", "position":3, "source":{"description":"Reference Data", "name":"REFERENCE", "code":"R"}, "sourceConfigurable":null, "label":"Unit/Unit of Issue", "formula":"", "indicator":"U", "used":true, "visible":true, "mandatory":false, "description":"Dispensing unit for this product", "formulaValidationRequired":true},
      {"id":4, "name":"beginningBalance", "position":4, "source":{"description":"User Input", "name":"USER_INPUT", "code":"U"}, "sourceConfigurable":null, "label":"Beginning Balancesadkjhfokasdnokasndokasndbosandjsandjkbsajkfbdsjfbsdjfbk", "formula":"", "indicator":"A", "used":true, "visible":true, "mandatory":false, "description":"Stock in hand of previous period.This is quantified in dispensing units", "formulaValidationRequired":true},
      {"id":5, "name":"quantityReceived", "position":5, "source":{"description":"User Input", "name":"USER_INPUT", "code":"U"}, "sourceConfigurable":null, "label":"Total Received Quantity", "formula":"", "indicator":"B", "used":true, "visible":true, "mandatory":false, "description":"Total quantity received in last period.This is quantified in dispensing units", "formulaValidationRequired":true},
      {"id":6, "name":"quantityDispensed", "position":6, "source":{"description":"User Input", "name":"USER_INPUT", "code":"U"}, "sourceConfigurable":null, "label":"Total Consumed Quantity", "formula":"A + B (+/-) D - E", "indicator":"C", "used":true, "visible":true, "mandatory":false, "description":"Quantity dispensed/consumed in last reporting  period. This is quantified in dispensing units", "formulaValidationRequired":true},
      {"id":7, "name":"lossesAndAdjustments", "position":7, "source":{"description":"User Input", "name":"USER_INPUT", "code":"U"}, "sourceConfigurable":null, "label":"Total Losses / Adjustments", "formula":"D1 + D2+D3...DN", "indicator":"D", "used":true, "visible":true, "mandatory":false, "description":"All kind of looses/adjustments made at the facility", "formulaValidationRequired":true},
      {"id":8, "name":"stockInHand", "position":8, "source":{"description":"Calculated", "name":"CALCULATED", "code":"C"}, "sourceConfigurable":null, "label":"Stock on Hand", "formula":"A+B(+/-)D-C", "indicator":"E", "used":true, "visible":true, "mandatory":false, "description":"Current physical count of stock on hand. This is quantified in dispensing units", "formulaValidationRequired":true},
      {"id":9, "name":"newPatientCount", "position":9, "source":{"description":"User Input", "name":"USER_INPUT", "code":"U"}, "sourceConfigurable":null, "label":"New Patients", "formula":"", "indicator":"F", "used":true, "visible":true, "mandatory":false, "description":"Total of new patients introduced", "formulaValidationRequired":true},
      {"id":10, "name":"stockOutDays", "position":10, "source":{"description":"User Input", "name":"USER_INPUT", "code":"U"}, "sourceConfigurable":null, "label":"Total Stockout days", "formula":"", "indicator":"X", "used":true, "visible":true, "mandatory":false, "description":"Total number of days facility was out of stock", "formulaValidationRequired":true},
      {"id":11, "name":"normalizedConsumption", "position":11, "source":{"description":"Calculated", "name":"CALCULATED", "code":"C"}, "sourceConfigurable":null, "label":"Adjusted Total Consumption", "formula":"C * (M*30)/((M*30)-X) + ( F* No of tabs per month * 1)", "indicator":"N", "used":true, "visible":true, "mandatory":false, "description":"Total quantity consumed after adjusting for stockout days. This is quantified in dispensing units", "formulaValidationRequired":true},
      {"id":12, "name":"amc", "position":12, "source":{"description":"Calculated", "name":"CALCULATED", "code":"C"}, "sourceConfigurable":null, "label":"Average Monthly Consumption(AMC)", "formula":"(N/M + Ng-1/M + ...Ng-(g-1)/M)/G", "indicator":"P", "used":true, "visible":true, "mandatory":false, "description":"Average Monthly consumption, for last three months. This is quantified in dispensing units", "formulaValidationRequired":true},
      {"id":13, "name":"maxStockQuantity", "position":13, "source":{"description":"Calculated", "name":"CALCULATED", "code":"C"}, "sourceConfigurable":null, "label":"Maximum Stock Quantity", "formula":"P * MaxMonthsStock", "indicator":"H", "used":true, "visible":true, "mandatory":false, "description":"Maximum Stock calculated based on consumption and max months of stock.This is quantified in dispensing units", "formulaValidationRequired":true},
      {"id":14, "name":"calculatedOrderQuantity", "position":14, "source":{"description":"Calculated", "name":"CALCULATED", "code":"C"}, "sourceConfigurable":null, "label":"Calculated Order Quantity", "formula":"H - E", "indicator":"I", "used":true, "visible":true, "mandatory":false, "description":"Actual Quantity needed after deducting stock in hand. This is quantified in dispensing units", "formulaValidationRequired":true},
      {"id":15, "name":"quantityRequested", "position":15, "source":{"description":"User Input", "name":"USER_INPUT", "code":"U"}, "sourceConfigurable":null, "label":"Requested Quantity", "formula":"", "indicator":"J", "used":true, "visible":true, "mandatory":false, "description":"Requested override of calculated quantity.This is quantified in dispensing units", "formulaValidationRequired":true},
      {"id":16, "name":"reasonForRequestedQuantity", "position":16, "source":{"description":"User Input", "name":"USER_INPUT", "code":"U"}, "sourceConfigurable":null, "label":"Requested Quantity Explanation", "formula":"", "indicator":"W", "used":true, "visible":true, "mandatory":false, "description":"Explanation of request for a quantity other than calculated order quantity", "formulaValidationRequired":true},
      {"id":17, "name":"quantityApproved", "position":17, "source":{"description":"User Input", "name":"USER_INPUT", "code":"U"}, "sourceConfigurable":null, "label":"Approved Quantity", "formula":"", "indicator":"K", "used":true, "visible":true, "mandatory":false, "description":"Final approved quantity. This is quantified in dispensing units", "formulaValidationRequired":true},
      {"id":18, "name":"packsToShip", "position":18, "source":{"description":"Calculated", "name":"CALCULATED", "code":"C"}, "sourceConfigurable":null, "label":"Packs to Ship", "formula":"K / U + Rounding rules", "indicator":"V", "used":true, "visible":true, "mandatory":false, "description":"Total packs to be shipped based on pack size and applying rounding rules", "formulaValidationRequired":true},
      {"id":19, "name":"price", "position":19, "source":{"description":"Reference Data", "name":"REFERENCE", "code":"R"}, "sourceConfigurable":null, "label":"Price per pack", "formula":"", "indicator":"T", "used":true, "visible":true, "mandatory":false, "description":"Price per Pack. It defaults to zero if not specified.", "formulaValidationRequired":true},
      {"id":20, "name":"cost", "position":20, "source":{"description":"Calculated", "name":"CALCULATED", "code":"C"}, "sourceConfigurable":null, "label":"Total cost", "formula":"V * T", "indicator":"Q", "used":true, "visible":true, "mandatory":false, "description":"Total cost of the product. This will be zero if price is not defined", "formulaValidationRequired":true},
      {"id":21, "name":"remarks", "position":21, "source":{"description":"User Input", "name":"USER_INPUT", "code":"U"}, "sourceConfigurable":null, "label":"Remarks", "formula":"", "indicator":"L", "used":true, "visible":true, "mandatory":false, "description":"Any additional remarks", "formulaValidationRequired":true}
    ];

  $scope.requisition = {"id":1, "facility":{"id":1, "code":"F10", "name":"Village Dispensary", "geographicZone":{"id":1, "name":"Arusha", "level":{"id":null, "name":"state"}, "parent":{"name":"Arusha", "level":{"id":null, "name":"state"}}}, "facilityType":{"id":1, "code":"warehouse", "name":"Warehouse", "description":"Central Supply Depot", "nominalMaxMonth":3, "nominalEop":0.5, "displayOrder":11, "active":true}, "operatedBy":{"id":2, "code":"NGO", "text":"NGO", "displayOrder":2}}, "program":{"id":1, "code":null, "name":"HIV", "description":null, "active":null}, "period":{"id":2, "scheduleId":null, "name":null, "description":null, "modifiedBy":null, "startDate":1351708200000, "endDate":1357324200000, "numberOfMonths":3, "modifiedDate":null}, "status":"INITIATED", "fullSupplyItemsSubmittedCost":"12.50", "nonFullSupplyItemsSubmittedCost":"0.00", "lineItems":[
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    
    
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg lorem ipsum lorem iprum", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"},
    
    
    
    
    {"id":2, "rnrId":1, "product":"antibiotic Capsule 300/200/600 mg", "productCode":"P12", "roundToZero":true, "packRoundingThreshold":1, "packSize":10, "dosesPerMonth":30, "dosesPerDispensingUnit":10, "dispensingUnit":"Strip", "maxMonthsOfStock":3, "fullSupply":true, "quantityReceived":89237498, "quantityDispensed":38472398, "beginningBalance":64375862, "totalLossesAndAdjustments":0, "stockInHand":115140962, "stockOutDays":23894723, "newPatientCount":39084093, "quantityRequested":4, "reasonForRequestedQuantity":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "amc":117252231, "normalizedConsumption":351756692, "calculatedOrderQuantity":236615731, "maxStockQuantity":351756693, "packsToShip":1, "remarks":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac mi enim. Donec commodo tristique risus ut vehicula. Sed vel mauris nec tortor pulvinar commodo ac quis ante.", "previousStockInHandAvailable":false, "price":"0.00"}
  ], "nonFullSupplyLineItems":[], "modifiedBy":200, "modifiedDate":1360233898779};

}

var splitTableForPrint = function () {

  if ($.browser.webkit) {
    $('body').addClass('webkit-print');
    $('table.splitForPrint').each(function (i, table) {
      var per_page = 14;

      var pages = Math.ceil($('tbody tr').length / per_page);

      if (pages == 1)
        return;

      var ultimo = $(table);
      for (var p = 1; p <= pages; p++) {
        var copy = ultimo.clone();

        $('tbody tr', ultimo).each(function (i, tr) {
          if (i >= per_page) {
            $(tr).remove();
          }
        });

        $('tbody tr', copy).each(function (i, tr) {
          if (i < per_page) {
            $(tr).remove();
          }
        });

        if (p < pages)
          copy.insertAfter(ultimo);

        copy.css('page-break-before', 'always');

        ultimo = copy;
      }
    });
    $('.splitForPrint').first().find('thead').css('visibility', 'visible');
  }
};

